---
development:
  cloud_name: coffeefriends
  api_key: '153533674293246'
  api_secret: WU2iXwh2bU5oxjmz-PHW65pCvGs 
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: coffeefriends
  api_key: '153533674293246'
  api_secret: WU2iXwh2bU5oxjmz
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: coffeefriends
  api_key: '153533674293246'
  api_secret: WU2iXwh2bU5oxjmz
  enhance_image_tag: true
  static_image_support: false
